server:
  port: 8282

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
    properties:
      schema.registry.url: http://localhost:8081

kafka:
  topic:
    customer-created: customer-created
    transaction-created: transaction-created